### ISSUE TITLE
Allow theming svg icons

### ISSUE THREAD

**Issue by instantaphex** [ag-grid/ag-grid#1982]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently I am not able to change the icon colors when using scss material theme despite the fact that the files are svg.  

**Expected behavior**
The icons should be included by inline-svg so that styling the svg is possible

**Minimal reproduction of the problem with instructions**
follow the instructions here:
https://www.ag-grid.com/javascript-grid-themes/material-theme.php#gsc.tab=0
to change the material theme colors, and the icons will all be black

**What is the motivation / use case for changing the behavior?**
To allow changing icon colors without having to copy icons into my project locally to override that which should already be overridable

**Please tell us about your environment:**
all

* **ag-Grid version:** X.X.X
13.3.1

* **Browser:**
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by mattrichard** [comment]
Same issue here. Attempting to change the icon colors results in them black.

I believe this is more of a bug than a feature request as the documentation says the theme colors can be changed.

**Comment by yohanroux** [comment]
Same Issue for me ...
$ag-mat-primary and $ag-mat-accent are well considered but not for svg icons ...

**Comment by piterchu** [comment]
I agree with @mattrichard it is more a bug than a feature.

Should be changed to bug

**Comment by petyosi** [comment]
Hi everyone, 

You are right - the mechanism for changing the default icon colors is there, but we did not fully implement it. I am logging this as AG-956 in our internal tracker. We will look into it soon.

**Comment by petyosi** [comment]
Hey everyone,

the feature is in `latest`, should be available in the next release. This is the implementation, in case you want to apply it before the release:
https://github.com/ag-grid/ag-grid/commit/d04fde4399b9657be5bdf53b86931ff7340a86a8

**Comment by petyosi** [comment]
You need this webpack loader for the `$icon-color` to work:

https://github.com/petyosi/svg-colorize-loader

**Comment by pathakparth** [comment]
I am facing the same issue. $icon-color property do not change the icon colors. Rest of the property are working fine for me as of now. @petyosi can you please provide a work around or fix for it. My company recently got license version  for ag-grid.

**Comment by Tolchi** [comment]
is there any solution without using webpack?

**Comment by iacii** [comment]
I chose to solve this by creating new SVG definitions in my CSS. I followed the example found here: [https://codepen.io/noahblon/post/coloring-svgs-in-css-background-images#data-uri-3](https://codepen.io/noahblon/post/coloring-svgs-in-css-background-images#data-uri-3).

I modified their functions slightly to look like this:

```scss
@function _buildIcon($icon) {
  $icon: '%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20xmlns%3Axlink%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxlink%22%20width%3D%2218px%22%20height%3D%2218px%22%3E#{$icon}%3C%2Fsvg%3E';
  @return $icon;
}

@function _buildPath($path, $parameters) {
  $icon: '%3Cpath%20fill%3D%22#{map-get($parameters, color)}%22%20fill-opacity%3D%22#{map-get($parameters, color-opacity)}%22%20stroke%3D%22#{map-get($parameters, stroke-color)}%22%20stroke-width%3D%22#{map-get($parameters, stroke-width)}%22%20style%3D%22#{map-get($parameters, css)}%22%20d%3D%22#{$path}%22%20%2F%3E';
  @return $icon;
}

@function icon(
  $icon-name,
  $color,
  $color-opacity: 1,
  $stroke-color: transparent,
  $stroke-width: 0,
  $css: '' // arbitrary css
  ){
    $parameters: (
      'color': $color,
      'color-opacity': $color-opacity,
      'stroke-color': $stroke-color,
      'stroke-width': $stroke-width,
      'css': $css
    );

    $icons: (
      checkbox-checked: _buildPath('M16 0H2a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM7 14L2 9l1.41-1.41L7 11.17l7.59-7.59L16 5l-9 9z', $parameters),
      checkbox-unchecked: _buildPath('M16 2v14H2V2h14zm0-2H2C.9 0 0 .9 0 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V2c0-1.1-.9-2-2-2z', $parameters)
    );

  $icon: _buildIcon(map-get($icons, $icon-name));
  @return url("data:image/svg+xml;charset=utf8,#{$icon}");
}
```

Then to use it in my SCSS theme file, I did the following:

```scss
.ag-theme-material .ag-icon-checkbox-checked:empty {
  $color: mat-color($accent);
  background-image: icon(checkbox-checked, '' + 'rgb(' + red($color) + ', ' + green($color) + ', ' + blue($color) + ')');
}
.ag-theme-material .ag-icon-checkbox-unchecked {
  $color: mat-color($foreground, icon);
  background-image: icon(checkbox-unchecked, '' + 'rgb(' + red($color) + ', ' + green($color) + ', ' + blue($color) + ')', opacity($color));
}
```
You can see this only supports checkbox-checked and checkbox-unchecked, but it can easily be expanded to include other icons.
