### ISSUE TITLE
Feature: multiline header cells with auto height

### ISSUE THREAD

**Issue by jledentu** [ag-grid/ag-grid#2361]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The height of header cells is fixed and can be changed with `setHeaderHeight`, but there is no option to set it automatically depending on the text content. There's an option `autoHeight=true` for rows but this cannot be used for headers.

**Expected behavior**
I'd like to have multiline header cells, with height set dynamically depending on the necessary space to display all the text.

**Minimal reproduction of the problem with instructions**
-

**What is the motivation / use case for changing the behavior?**
It seems important, in my case, to display long header labels on several lines.

**Please tell us about your environment:**
Ubuntu 17.10
VS Code
npm
Vue 2.5

* **ag-Grid version:** 17.1.1

* **Browser:**
All browsers

* **Language:** ES2015+

**Comment by khelal** [comment]
+1

**Comment by jaetea** [comment]
Need this.

**Comment by hugobaes** [comment]
+1.

If anyone find a CSS solution, please share! =)

**Comment by jledentu** [comment]
I may have found a solution: https://next.plnkr.co/edit/GLWuXQte1Ub6ckIE

I set some CSS properties on header text elements:

```js
.ag-theme-balham .multiline .ag-header-cell-label .ag-header-cell-text {
    text-overflow: clip;
    overflow: visible;
    white-space: normal;
    height: auto;
}
```

And compute the maximum `scrollHeight`of all header labels, on some events (`onColumnResized`, `onGridReady`):

```js
const MIN_HEIGHT = 25;

function autosizeHeaders(event) {
    if (event.finished !== false) {
        event.api.setHeaderHeight(MIN_HEIGHT);
        const headerCells = document.querySelectorAll('#myGrid .ag-header-cell-label');
        let minHeight = MIN_HEIGHT;
        headerCells.forEach(cell => {
            minHeight = Math.max(minHeight, cell.scrollHeight);
        });
        event.api.setHeaderHeight(minHeight);
    }
}
```

Feel free to test this code and tell me if you meet any issue! 😉

**Comment by Sarah4VT** [comment]
+1

**Comment by makinggoodsoftware** [comment]
Hi,

This is briliant! Thanks @jledentu 

I am going to add this thread into zendesk to consider to bring this change into the core

Thanks 👍

**Comment by makinggoodsoftware** [comment]
Hi,

Your ticket has been flagged as in_zendesk, it means that we recognize this as an issue worth investigating so we have moved it to our official support channel for customers (zendesk)

We will carry on there with the investigation and we will update you as soon as possible.

Thanks

**Comment by MrLumbergh** [comment]
> 
> Feel free to test this code and tell me if you meet any issue! 😉

The solution works, but the line-height is much too height! It's 56px and I have no clue how to get it smaller without having other issues...any idea?

**Comment by Sarah4VT** [comment]
I have the same problem with the line height. I tried overwriting .ag-theme-material .ag-header-cell with a line-height: normal but my icons for sorting and filtering are not displaying well.

**Comment by makinggoodsoftware** [comment]
Hi,

Thank you for your email. We are aware of this issue and have a feature request in our backlog:

You can follow the status of feature requests, bugs and releases using our pipeline: 
https://www.ag-grid.com/ag-grid-pipeline/

If you are an ag-Grid Enterprise Customer, please raise this in our Zendesk support system - contact info@ag-grid.com for access. This is our primary channel for Support.



This is the reference and summary of the relevant issue:



AG-2142
Add autoHeight for headers

**Comment by cuongncdn** [comment]
thanks @jledentu

**Comment by slorion** [comment]
Thanks a lot @jledentu  ! I iterated on your solution to reduce default line-height/padding and also make header separator taller:

```css
/* reduce ag-grid default header line-height and padding */
.ag-theme-balham .ag-header-cell {
    line-height: normal;
    padding: 8px;
}

/* make header separator height proportional to header height */
.ag-theme-balham .ag-header-cell:after,
.ag-theme-balham .ag-header-group-cell:after {
    height: 50%;
}

/* set icons height to their real absolute value to ensure proper vertical alignment */
.ag-theme-balham .ag-header-cell-menu-button .ag-icon-menu,
.ag-theme-balham .ag-header-cell-label .ag-header-icon {
    height: 16px;
}

/* make header text wrap, without breaking words and without ellipsis */
 .ag-theme-balham .ag-header-cell-label .ag-header-cell-text {
    height: auto;
    overflow: visible;
    overflow-wrap: normal;
    text-overflow: clip;
    white-space: normal;
}
```

```javascript
const MIN_HEIGHT = 16;

function autosizeHeaders(event) {
    if (event.finished !== false) {
        event.api.setHeaderHeight(MIN_HEIGHT);
        const headerCells = document.querySelectorAll('#myGrid .ag-header-cell-label');
        let minHeight = MIN_HEIGHT;
        headerCells.forEach(cell => {
            minHeight = Math.max(minHeight, cell.scrollHeight);
        });

        // set header height to calculated height + padding (top: 8px, bottom: 8px)
        event.api.setHeaderHeight(minHeight + 16);
    }
}
```
