### ISSUE TITLE
Bootstrap theme is terrible

### ISSUE THREAD

**Issue by dflock** [ag-grid/ag-grid#2819]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

The current bootstrap theme doesn't do a very good job - and doesn't integrate with bootstrap very well at all. See comments on #34.

This is an attempt at improving the styles a bit. This is aimed at matching bootstrap tables that use the `.table-striped` class, but not `.table-bordered`. It's a scss file and assumes that you have the relevant bootstrap scss files in your project, allowing you to use the bootstrap scss variables etc...

```scss
//
// Improve agGrid bootstrap theme
//
$ag-icons-path: '../node_modules/ag-grid-community/src/styles/icons/';

$font-family: var(--font-family-sans-serif);
$font-weight: 400;

$secondary-font-family: var(--font-family-sans-serif);
$secondary-font-weight: 700;

$grid-size: 4px;
$row-height: $grid-size * 6 + 4;
$header-height: $row-height;

@import '~ag-grid-community/src/styles/ag-grid';
@import '~ag-grid-community/src/styles/ag-theme-bootstrap';

.ag-theme-bootstrap {
  margin-bottom: 1rem;

  // TODO: make this contingent on boostrap .table-bordered
  .ag-root {
    border: 0;
  }

  .ag-header {
    border-bottom: 1px solid $table-border-color;

    .ag-header-row,
    .ag-header-cell {
      border: 0;
      cursor: pointer;
    }
    .ag-header-cell {
      border-top: 1px solid $table-border-color;
    }
  }

  // By default the agGrid row stripes are the opposite way round from the boostrap ones
  .ag-row-even {
    // background-color: $table-accent-bg;
    // Should be this ^^, but that gets you #EAEAEA,
    // which isn't what bootstrap seems to use???
    background-color: #f2f2f2;
  }
  .ag-row-odd {
    background-color: $white;
  }

  .ag-cell {
    border-top: 1px solid $table-border-color;
  }

  .ag-ltr .ag-cell-focus {
    border: 1px dotted $table-border-color;
  }
}
```
