### ISSUE TITLE
Dynamic font-size variable values

### ISSUE THREAD

**Issue by artu-ole** [ag-grid/ag-grid#4121]
**I'm submitting a ...**
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of ag-Grid'
[] support request => see 'Requesting Community Support'
```

I've just picked up ag-grid therefore I might be missing a customization option or a workaround that would allow this, however:

**Current behavior**
Changing theme's font-size to `em` value introduces incorrect scaling issues:
```scss
@import "../../node_modules/ag-grid-community/src/styles/ag-grid.scss";
@import "../../node_modules/ag-grid-community/src/styles/ag-theme-alpine/sass/ag-theme-alpine-mixin.scss";

.ag-theme-alpine {
  @include ag-theme-alpine((
    font-size: 1em
  ));
}
```
![image](https://user-images.githubusercontent.com/15938416/95341867-6f0f9500-08bf-11eb-8056-774d93f46d58.png)

due to mixin code being:
```scss
    .ag-row {
        font-size: ag-param(font-size) + 1;
    }
```
this results in `font-size: 2em`

**Expected behavior**
![image](https://user-images.githubusercontent.com/15938416/95343285-032e2c00-08c1-11eb-91a4-e0435fc7ecc7.png)

Expected `font-size: calc(1em + 1px)` to match the pixels behavior.
Mixins would need to be changed to something along the lines of:
```scss
    .ag-row {
        font-size: calc(#{ag-param(font-size)} + 1px);
    }
```

There are several places that would result in the error
![image](https://user-images.githubusercontent.com/15938416/95342774-75524100-08c0-11eb-994e-59fb2ec9d8a1.png)

**Please tell us about your environment:**

* **ag-Grid-community version:** 24.0.0
* **ag-Grid-angular version:** 24.0.0
