### ISSUE TITLE
[performance] Scrolling performance on iPad (ios) could be better

### ISSUE THREAD

**Issue by daghoidahl** [ag-grid/ag-grid#550]
On my iPad, the scroll experience of ag-grid is jagged and uneven. I need to keep dragging the contents in the table area instead of just flicking as for other browser content. (Scrolling performance for the same tables is generally very good on my desktop browser, so I don't believe it is a case of "heavy" table contents.) It is easy to reproduce this by trying to scroll the Test Drive table, for instance. 

[This Stack Overflow answer](http://stackoverflow.com/a/33544122/22146) provides a solution, which is to add this css directive:

``` css
.ag-body-viewport {
  /* Use momentum-based scrolling on WebKit-based touch devices. */
  -webkit-overflow-scrolling: touch;
}
```
