### ISSUE TITLE
Broken .ag-cell class styles

### ISSUE THREAD

**Issue by shadoworion** [ag-grid/ag-grid#5661]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => see 'Providing a Reproducible Scenario'
```

**Current behavior**
Since the last update, the vertical position of all values is on the top.

**Expected behavior**
Before the last update, it was in the middle. 
For now, I fix it with this CSS:
```css
.ag-cell {
  display: flex;
  align-items: center;
  overflow: hidden;
}
```

* **AG Grid version:** 28.2.0

* **Language:** TypeScript, React, Vite
