### ISSUE TITLE
how to apply tailwind CSS in ag-grid ?

### ISSUE THREAD

**Issue by codingwithashu** [ag-grid/ag-grid#7044]
I am creating a Dashboard where I need a uniform UI, Can anyone suggest how to apply tailwind CSS in ag-grid?

**Comment by joemaylor** [comment]
You should be able to use [taliwind's `theme()` function](https://tailwindcss.com/docs/functions-and-directives#theme) along with [Ag-Grid's provided CSS variables](https://www.ag-grid.com/angular-data-grid/global-style-customisation/)

e.g.
```css
.ag-theme-alpine {
    --ag-background-color: theme(colors.blue.500);
}
```
