### ISSUE TITLE
Icons not loading

### ISSUE THREAD

**Issue by sdasswift** [ag-grid/ag-grid#7952]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```
**Requesting Community Support**

If you are not a customer of AG Grid, ag-grid staff will label your issue as managed-by-the-community. This means that AG Grid staff is not going to be actively looking into it and it will get closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are
- A description of the detailed steps to reproduce your behaviour in one of our examples in the docs.
- A plunker

If you decide to send us a plunker, from any example in our website use the plunker button in there to fork your own code by following the steps below:

- Select the framework that is appropriate to you from the drop-down
- Open it in plunker. (Use the button plunker in our example)
- Add your changes so that the behaviour is reproduced
- Save and Freeze the plunker(On the top left corner)
- Send us the link to the plunker(You can copy the URL from the browser)

If reporting a bug make sure to state.

Current behaviour.
Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
Sometimes the icons are not loading properly when deployed to our servers

![image](https://github.com/ag-grid/ag-grid/assets/164323080/30935c81-c8c6-4097-9bf6-f80d3400d513)

**Expected behavior**
Icons should be loaded properly

* **AG Grid version:** X.X.X
31.2.1

* **Browser:**
Chrome

* **Language:**  Typescript

**Comment by AG-Zoheil** [comment]
Hi

Thank you for reporting this.

We'd be happy to look into this, but the most efficient way for us to do so would be for you to provide a live example reproducing the issue.

Please send us a live plunker sample which shows the issue. You can use one of the examples from our website as a starting point. Do let us know if you need further guidance on this.

We're looking forward to your response.

Kind regards,
Zoheil

**Comment by sdasswift** [comment]
Hi, 

Thanks for responding back quickly.

It's an intermittent issue actually and it's hard to reproduce it manually. I keep my network tab open always, next time it happens, I'll see the network and will report back to you, if I see any discrepancy.

Thanks
Soumyanil

**Comment by evheniyrz** [comment]
checkbox icons in cell are not displayed with initial settings
![image](https://github.com/ag-grid/ag-grid/assets/42120738/96b9e2c4-a588-4a82-b6d2-0d336599d0c5)
stackblitz: https://stackblitz.com/~/github.com/evheniyrz/angular-cdk-drag-handle

Angular: ^17.3.7
Ag-Grid: 
    "ag-grid-angular": "^31.3.1",
    "ag-grid-community": "^31.3.1",
Component:
src/app/pages/ag-grid-tutorial/components/table/table.component.ts

Angular.json

```
"styles": [
              "node_modules/ag-grid-community/styles/ag-grid.css",
              "node_modules/ag-grid-community/styles/ag-theme-quartz.css",
              "@angular/material/prebuilt-themes/pink-bluegrey.css",
              "src/styles.scss"
            ],
```

**Comment by BernieSumption** [comment]
The cause of the issue is in `src/styles.scss`.

```scss
*,
*::after,
*::before {
  box-sizing: border-box;
  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
    Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
}
```

Ag Grid uses icon fonts to render icons, and by setting the font on `*::after` you remove the icon font icons and checkboxes.

We'll make a change to the grid styles to make them less susceptible to this kind of thing, but in the mean time using this instead works:

```scss
*,
*::after,
*::before {
  box-sizing: border-box;
}
* {
  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
    Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
}
```
